// <auto-generated />
using InsurancePolicies.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsurancePolicies.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250501223548_RenameInsurancePolicyTable")]
    partial class RenameInsurancePolicyTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsurancePolicies.Models.InsurancePolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PolicyHolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PremiumAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Policy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            PolicyHolderName = "John Mwangi",
                            PolicyNumber = "POL123456",
                            PolicyType = "Health",
                            PremiumAmount = 15000.00m
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            PolicyHolderName = "Alice Wanjiku",
                            PolicyNumber = "POL234567",
                            PolicyType = "Life",
                            PremiumAmount = 25000.00m
                        },
                        new
                        {
                            Id = 3,
                            IsActive = false,
                            PolicyHolderName = "Brian Otieno",
                            PolicyNumber = "POL345678",
                            PolicyType = "Vehicle",
                            PremiumAmount = 8000.50m
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            PolicyHolderName = "Faith Njeri",
                            PolicyNumber = "POL456789",
                            PolicyType = "Home",
                            PremiumAmount = 12000.75m
                        },
                        new
                        {
                            Id = 5,
                            IsActive = false,
                            PolicyHolderName = "Elvis Kiptoo",
                            PolicyNumber = "POL567890",
                            PolicyType = "Travel",
                            PremiumAmount = 6000.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
